version: '3.9'
services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./data:/var/lib/mysql
    restart: on-failure
    env_file: .env
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${HOST}:${DATABASE_PORT}:3306"
    networks:
      - djangonet

  django:
    depends_on:
      - "mariadb"
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./product_tracker:/code
      - ./product_tracker/static:/code/static
    env_file: .env
    # command: "ls ../"
    command: "chmod +x ../entrypoint.sh"
    ports:
      - "${HOST}:${DJANGO_PORT}:8000"
    links:
      - mariadb
    networks:
      - djangonet

  phpmyadmin:
    depends_on:
      - "mariadb"
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
      HIDE_PHP_VERSION: 1
    ports:
      - "${HOST}:${PHPMYADMIN_PORT}:80"
    networks:
      - djangonet

networks:
  djangonet:
    driver: bridge