version: '3.9'
services:
  portainer-ce:
    image: portainer/portainer-ce:2.6.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always
    ports:
      # - "127.0.0.1:8001:9000"
      # - "127.0.0.1:8002:8000"
      - "${HOST}:8001:9000"
      - "${HOST}:8002:8000"