version: '3.8'
services:
  jupyter-book:
    build: .
    volumes:
      - ./business-plan/:/jupyter/business-plan/
      - ./Doc/:/jupyter/Doc/
      - ./necronomicon/:/jupyter/necronomicon/
      - ./NNASS-doc/:/jupyter/NNASS-doc/
      - ./Separacao-de-Fonte-Sonora-Doc/:/jupyter/Separacao-de-Fonte-Sonora-Doc/
    restart: always
    # command: jupyter-book toc migrate /home/_toc.yml -o /home/_toc.yml

  httpd:
    image: httpd:latest
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./business-plan/_build/html/:/usr/local/apache2/htdocs/business-plan/
      - ./Doc/_build/html/:/usr/local/apache2/htdocs/Doc/
      - ./necronomicon/_build/html/:/usr/local/apache2/htdocs/necronomicon/
      - ./NNASS-doc/_build/html/:/usr/local/apache2/htdocs/NNASS-doc/
      - ./Separacao-de-Fonte-Sonora-Doc/_build/html/:/usr/local/apache2/htdocs/Separacao-de-Fonte-Sonora-Doc/
    restart: always
    ports:
      - "${HOST}:80"
    depends_on:
      - "jupyter-book"